"""Add phone_number to User

Revision ID: 0e1b848f0ccf
Revises: cb288a00a29c
Create Date: 2026-05-14 22:13:47.828650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1b848f0ccf'
down_revision: Union[str, None] = 'cb288a00a29c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('metrics_timestamp_idx'), table_name='metrics')
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=False))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'phone_number')
    op.create_index(op.f('metrics_timestamp_idx'), 'metrics', [sa.literal_column('timestamp DESC')], unique=False)
    # ### end Alembic commands ###
